import React from "react";
import { Document, Page, Text, View, StyleSheet, Image } from "@react-pdf/renderer";
import { Transaction } from "../context/FinanceContext";

// Create styles for the PDF
const styles = StyleSheet.create({
  page: {
    padding: 30,
    fontFamily: "Courier",
    backgroundColor: "#ffffff",
    color: "#000000",
    fontSize: 10,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 20,
  },
  logoContainer: {
    flex: 1,
    paddingRight: 20,
    maxHeight: 60,
  },
  logo: {
    objectFit: "contain",
    objectPosition: "left",
    maxHeight: 60,
  },
  companyName: {
    fontSize: 18,
    fontWeight: "bold",
    fontFamily: "Courier-Bold",
  },
  statementInfo: {
    alignItems: "flex-end",
  },
  titleLine: {
    fontSize: 12,
    fontFamily: "Courier-Bold",
    marginTop: 20,
    marginBottom: 10,
    textTransform: "uppercase",
  },
  table: {
    display: "flex",
    width: "100%",
  },
  tableHeader: {
    flexDirection: "row",
    borderBottomWidth: 1,
    borderBottomColor: "#000",
    borderBottomStyle: "dashed",
    borderTopWidth: 1,
    borderTopColor: "#000",
    borderTopStyle: "dashed",
    paddingVertical: 5,
    marginBottom: 5,
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 3,
  },
  colDate: { width: "12%" },
  colTime: { width: "10%" },
  colParty: { width: "25%" },
  colPurpose: { width: "38%" },
  colAmount: { width: "15%", textAlign: "right" },
  tableCellHeader: {
    fontSize: 9,
    fontFamily: "Courier-Bold",
  },
  tableCell: {
    fontSize: 9,
  },
  tableCellAmount: {
    fontSize: 9,
    textAlign: "right",
  },
  balanceRow: {
    flexDirection: "row",
    paddingVertical: 5,
    marginBottom: 5,
    borderBottomWidth: 1,
    borderBottomColor: "#000",
    borderBottomStyle: "dotted",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: "center",
    fontSize: 8,
    borderTopWidth: 1,
    borderTopColor: "#000",
    borderTopStyle: "dashed",
    paddingTop: 5,
  },
});

interface ReportPdfProps {
  transactions: Transaction[];
  startingBalance: number;
  dateFilter: string;
  companyProfile: {
    name: string;
    logoUrl: string | null;
  };
  generatedBy: string;
  reportTotals: {
    totalCashIn: number;
    totalIncome: number;
    totalExpense: number;
    netFlow: number;
  };
}

export const ReportPdf: React.FC<ReportPdfProps> = ({
  transactions,
  startingBalance,
  dateFilter,
  companyProfile,
  generatedBy,
  reportTotals,
}) => {
  const formatAmount = (val: number) => {
    return val.toLocaleString("en-BD", {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    });
  };

  const getFilterLabel = () => {
    switch (dateFilter) {
      case "today": return "TODAY";
      case "week": return "THIS WEEK";
      case "month": return "THIS MONTH";
      case "year": return "THIS YEAR";
      case "custom": return "CUSTOM RANGE";
      case "all": return "ALL TIME";
      default: return dateFilter.toUpperCase();
    }
  };

  const now = new Date();
  const currentDate = now.toLocaleDateString("en-GB", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  }).replace(/ /g, "-");
  
  const currentTime = now.toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
    hour12: true,
  });

  return (
    <Document>
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <View style={styles.logoContainer}>
            {companyProfile.logoUrl ? (
              <Image style={styles.logo} src={companyProfile.logoUrl} />
            ) : (
              <Text style={styles.companyName}>{companyProfile.name.toUpperCase()}</Text>
            )}
          </View>
          <View style={styles.statementInfo}>
            <Text>PRINT DATE: {currentDate}</Text>
            <Text>PRINT TIME: {currentTime}</Text>
            {generatedBy && <Text>GENERATED BY: {generatedBy.toUpperCase()}</Text>}
          </View>
        </View>
        
        {companyProfile.logoUrl && (
          <Text style={{ ...styles.companyName, marginBottom: 10 }}>
            {companyProfile.name.toUpperCase()}
          </Text>
        )}

        <Text style={styles.titleLine}>
          STATEMENT OF ACCOUNT FOR THE PERIOD OF {getFilterLabel()}
        </Text>

        {/* Transactions Table */}
        <View style={styles.table}>
          {/* Table Header */}
          <View style={styles.tableHeader}>
            <View style={styles.colDate}><Text style={styles.tableCellHeader}>DATE</Text></View>
            <View style={styles.colTime}><Text style={styles.tableCellHeader}>TIME</Text></View>
            <View style={styles.colParty}><Text style={styles.tableCellHeader}>PARTY</Text></View>
            <View style={styles.colPurpose}><Text style={styles.tableCellHeader}>PURPOSE</Text></View>
            <View style={styles.colAmount}><Text style={styles.tableCellHeader}>AMOUNT</Text></View>
          </View>

          {/* Starting Balance */}
          <View style={styles.balanceRow}>
            <View style={{ width: "85%" }}>
              <Text style={styles.tableCell}>Balance Forward</Text>
            </View>
            <View style={styles.colAmount}>
              <Text style={styles.tableCellAmount}>{formatAmount(startingBalance)}</Text>
            </View>
          </View>

          {/* Table Rows */}
          {transactions.map((tx, i) => {
            const isPositive = tx.type === "cash_in" || tx.type === "income";
            const party = tx.type === "expense" ? tx.receiver : tx.payer;
            const sign = isPositive ? "" : "-";
            
            return (
              <View key={tx.id} style={styles.tableRow}>
                <View style={styles.colDate}>
                  <Text style={styles.tableCell}>{tx.date}</Text>
                </View>
                <View style={styles.colTime}>
                  <Text style={styles.tableCell}>{tx.time}</Text>
                </View>
                <View style={styles.colParty}>
                  <Text style={styles.tableCell}>{party}</Text>
                </View>
                <View style={styles.colPurpose}>
                  <Text style={styles.tableCell}>{tx.purpose}</Text>
                </View>
                <View style={styles.colAmount}>
                  <Text style={styles.tableCellAmount}>
                    {sign}{formatAmount(tx.amount)}
                  </Text>
                </View>
              </View>
            );
          })}
          
          {/* Statement Period Totals */}
          <View style={[styles.tableRow, { borderTopWidth: 1, borderTopStyle: "dashed", borderTopColor: "#000", marginTop: 5, paddingTop: 5 }]}>
            <View style={{ flex: 1 }}>
              <Text style={styles.tableCellHeader}>
                PERIOD TOTALS - CASH IN: {formatAmount(reportTotals.totalCashIn)} | INCOME: {formatAmount(reportTotals.totalIncome)} | EXPENSE: {formatAmount(reportTotals.totalExpense)}
              </Text>
            </View>
          </View>
        </View>

        {/* Footer */}
        <View style={styles.footer} fixed>
          <Text>*** END OF STATEMENT ***</Text>
        </View>
      </Page>
    </Document>
  );
};
